// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cigfiyqblaehlfohzjbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZ2ZpeXFibGFlaGxmb2h6amJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzOTA4MjMsImV4cCI6MjA5MDk2NjgyM30.G327VjOctU6zKEzUPyfBz1F6T3-BZfQUGcbveHAAohQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});